FROM node:26-alpine AS tw
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY public/globals.css style.css
COPY public/tailwind.config.js tailwind.config.js
COPY templates/ templates/
RUN npx @tailwindcss/cli -i style.css -o main.css --minify


FROM rust:1.95-slim-bookworm AS builder
WORKDIR /app

# cache
COPY Cargo.lock Cargo.toml ./
RUN \
  --mount=type=cache,target=/app/target/ \
  --mount=type=cache,target=/usr/local/cargo/registry/ \
  mkdir src \
  && echo "fn main() {}" > src/main.rs \
  && cargo fetch \
  && rm -rf src

# build
COPY src ./src
COPY public ./public
RUN \
  --mount=type=cache,target=/app/target/ \
  --mount=type=cache,target=/usr/local/cargo/registry/ \
  cargo build --release \
  && cp ./target/release/portfolio /


FROM debian:bookworm-slim AS deploy
WORKDIR /opt/app

RUN adduser \
  --disabled-password \
  --gecos "" \
  --home "/nonexistent" \
  --shell "/sbin/nologin" \
  --no-create-home \
  --uid "10001" \
  appuser

COPY --from=builder /portfolio /usr/local/bin
RUN chown appuser /usr/local/bin/portfolio && chown -R appuser /opt/app

COPY templates ./templates/
COPY public ./public/
COPY --from=tw /app/main.css ./public/css/main.css

USER appuser
ENV RUST_LOG="portfolio=debug,info"
ENV RUST_BACKTRACE=1

EXPOSE 80
ENTRYPOINT ["/usr/local/bin/portfolio"]
