import '@styles/globals.css'

import { cn } from '@utils/tailwind'
import { ThemeProvider } from '@components/theme-provider'

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

import Navbar from '@components/navbar'
import Footer from '@components/footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={cn(inter.className, 'min-h-screen min-w-full max-w-full flex flex-col')}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout
