name: Linting

on:
  push:
    branches:
      - main
      - v*
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  changed-files:
    name: Changed Files
    runs-on: ubuntu-latest
    outputs:
      lint-rust: ${{ steps.changed-files.outputs.lint-rust_any_modified == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits

      - name: Find changed files
        uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files_yaml: |
            common: &common
              - .github/workflows/linting.yml
              - Makefile

            lint-rust:
              - *common
              - src/**
              - Cargo.toml
              - Cargo.lock
  rust:
    name: Rust
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: ${{ needs.changed-files.outputs.lint-rust == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ./target
          key: rust-${{ hashFiles('Cargo.lock') }}
          restore-keys: rust

      - name: Setup Rust
        run: |
          set -xe
          rustup update stable
          rustup default stable

      - name: Install dependencies
        run: |
          set -xe
          make install/cargo

      - name: Lint
        run: |
          set -xe
          make lint

  check:
    if: always()
    name: Linting Successful
    runs-on: ubuntu-latest
    needs: [npm, rust]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}
