name: "Testing"

on:
  push:
    branches:
      - main
      - v*
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ./target
          key: rust-${{ hashFiles('Cargo.lock') }}
          restore-keys: rust

      - name: Setup Rust
        run: |
          set -xe
          rustup update stable
          rustup default stable

      - name: Install dependencies
        run: |
          set -xe
          make install/cargo

      - name: Testing
        run: |
          set -xe
          make test
